### ISSUE TITLE
Problem with Restyler Job #341892

### ISSUE THREAD

**Issue by grugnog** [restyled-io/restyler#111]
Hi there-

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/CivicActions/repos/handbook/jobs/341892
- **GitHub PR**: CivicActions/handbook#610

**What I expected to happen**:

Job to complete with no changes (commit was a minor wording tweak on a PR that had already passed Restyler).

**What happened instead**:

Job failed with no output.

**Configuration**: https://github.com/CivicActions/handbook/blob/master/.restyled.yaml

**Comment by pbrisbin** [comment]
Hi, so sorry for the trouble with this Job. We've been moving our infrastructure between AWS accounts, and improving some thigns along the way (that I hope to blog about soon!), which has unfortunately caused a little disruption here and there and is probably what caused this build to fail this way. There's no guarantees we won't have operational issues in the future, but this particular move is finishing up now, so I'd expect things to be resolved.

Looking at the [builds for that PR](https://restyled.io/gh/CivicActions/repos/handbook/pulls/610/jobs) and the [builds for that Repo](https://restyled.io/gh/CivicActions/repos/handbook/jobs), it looks like things are succeeding before and after this one, which tells me it's not anything systemic or an issue with your code or configuration.

Again, very sorry and hopefully it won't happen again going forward.

**Comment by grugnog** [comment]
@pbrisbin no problem - just letting you know about a glitch (the issue reporting worked nicely!). Thanks for the service and making it FOSS - I am a huge fan :)
