### ISSUE TITLE
Automatically generate a .git-blame-ignore file

### ISSUE THREAD

**Issue by pbrisbin** [restyled-io/restyler#112]
https://twitter.com/steipete/status/1295631436951756802?s=19

Git supports a file where you can place shas to be ignored (skipped over) by `git-blame`. This is useful for style-fixing commits, such as the ones Restyled creates. We could add a sub-command to look for our own commits and create or update such a file in a PR whenever we see one on a merge to the default-branch.

This would require a few architectural changes:

- We need the CLI to support sub-commands, or make a separate executable
- We need to expand our webhook filter to not discard the merge events

And a few product decisions:

- How could one configure this? (we need to know the file name and the user needs to have `git config`ed it)

  Maybe we could look for files of some conventional names, and act only if such a file exists. Opting-in would then mean creating this file.

- Is this even valuable given that every user needs to `git config` it themselves before it works?

**Comment by pbrisbin** [comment]
So, I think we shouldn't do this. Interested users can do it themselves pretty easily:

```console
git log --author=commits@restyled.io --format="%H # %s" > .git-blame-ignore-revs
git config blame.ignoreRevsFile .git-blame-ignore-revs
```

This creates a file like:

```
9c004362a93ed699622e8043ae79cf21617e63fa # Restyled by brittany
ca52b4573f50258c3c03a2bb8a60780ebeac2d1e # Restyled by whitespace
9f16d88031d390fd25be85253cc14a351bdf8666 # Restyled by whitespace
f70a961acf396d1db9d230f24dabccb4032461d7 # Restyled by whitespace
1a3a83c6a095fedf254fd13e6ca05f2440455e0c # Restyled by whitespace
7e402ba04fd3196c983539827f43b42d34c5a748 # Restyled by whitespace
e0a3b656ddc43a11622c88b52668e92ad191e677 # Restyled by whitespace
...
```

**Comment by stackptr** [comment]
Github uses the `.git-blame-ignore-revs` for its [blame UI beta](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view):

<img width="543" alt="Screen Shot 2022-05-13 at 11 22 16 AM" src="https://user-images.githubusercontent.com/4542907/168344225-f06e2f3b-ae32-4535-aefb-1ff1c150b091.png">

If the beta is adopted, it would provide a sensible default and would give some benefit to a user without the burden of configuration, though they'd still need to configure locally.
