### ISSUE TITLE
Docker image version skew may result

### ISSUE THREAD

**Issue by rwalker-apple** [restyled-io/restyler#122]
#### Problem
Using restyle-path on a local development machine, which typically has cached Docker images, can result in version skew because restyle-path uses a symbolic tag for the version it wants.

For example:
```
restyle-path: ConfigErrorInvalidRestylersYaml (AesonException "Error in $[0]: - Unexpected key \"metadata\", must be one of [\"enabled\",\"name\",\"image\",\"command\",\"arguments\",\"include\",\"interpreters\",\"delimiters\",\"supports_arg_sep\",\"supports_multiple_paths\",\"documentation\"].\n")
```

#### Proposed Solution
Use an explicit version here:

https://github.com/restyled-io/restyler/blob/f3e2396801b1f0f7449ea1f44ac272ee2994ba33/bin/restyle-path#L33

Instead of a symbolic tag.

**Comment by pbrisbin** [comment]
It's expected this drift would exist, and is the reason `-p` exists. I'm open to revisit, but last I weighed it, the effort to keep an explicit sha or version tag up to date like that was not worth it.

I rarely make incompatible changes to the manifest or config like that, but I just happened to recently.

**Comment by pbrisbin** [comment]
Also, doing that would just move the drift elsewhere. I'd expect users typically `curl` this source file to their system, and not symlink it into `$PATH` from a clone of the restyler repository. And even if they did use the clone, they'd have to `git pull` to get the version updates too.

It's a tricky problem. We're in a sort of uncanny valley where this was primarily a "me" tool, so in no way a proper, versioned, installable thing. But I'm finding more an more folks find it useful, so maybe it needs to be.

**Comment by rwalker-apple** [comment]
Ah, just remembered you did all that ymmy extra stuff in there.  Wonder if `-p` should be the default.  Seems a near-zero-cost step if the image is up to date.

**Comment by pbrisbin** [comment]
> Wonder if -p should be the default. Seems a near-zero-cost step if the image is up to date.

That's fair! I like it.

**Comment by rwalker-apple** [comment]
Here's our usage:  https://github.com/project-chip/connectedhomeip/blob/master/scripts/helpers/restyle-diff.sh
