### ISSUE TITLE
Bump clang-formatter docker image version from 10.0.0.2 to >= 11

### ISSUE THREAD

**Issue by RalphSteinhagen** [restyled-io/restyler#134]
Thanks for this great project and restyler bot which we are happily using in several of our open-source projects.

We moved to C++17/20 and are thus also using newer clang/clang-format versions. The formatter has a slightly different config syntax than the one you provide in the above-mentioned docker image. 

Would it be possible to bump the docker image you provide for clang-format to 11 or any other newer version?

Many thanks in advance and much appreciated. :v: :+1:

**Comment by pbrisbin** [comment]
Well, I ended up having some time. https://github.com/restyled-io/restylers/pull/175

I'll try to get this merged and released in stable this week.

**Comment by pbrisbin** [comment]
clang-format-12 is available in the Dev channel now,

- https://docs.restyled.io/available-restylers/?channel=dev
- https://github.com/restyled-io/restyled.io/wiki/Restyler-Versions#opt-in-to-newer-earlier 

I'm going to batch up a few more updates coming in before promoting to Stable, but am closing this issue now.

**Comment by RalphSteinhagen** [comment]
@pbrisbin thanks a lot for the quick help! Much appreciated and I owe you one! :+1:
