### ISSUE TITLE
Problem with Restyler Job #1097712

### ISSUE THREAD

**Issue by mleisner** [restyled-io/restyler#155]
Please use the below template to report an issue with this Job. **Don't submit
sensitive information**, this is a public project. If you'd rather communicate
privately, email support@restyled.io.

---

Hi there-

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/project-chip/repos/connectedhomeip/jobs/1097712
- **GitHub PR**: project-chip/connectedhomeip#9405

something meaningful

**What happened instead**:
stderrDigest: sha256:f823074ec6bb8565eab34c8c1e7d4b162724454ef3b041e505b0bdb8a3dc3f10
stderrStatus: Downloaded newer image for restyled/restyler-gn:v1
stderrTo https://github.com/project-chip/connectedhomeip.git
stdoutSetting status of error for 5dcc1b3
stderr ! [remote rejected]     restyled/pull-9405 -> restyled/pull-9405 (refusing to allow a GitHub App to create or update workflow `.github/workflows/examples-nrfconnect.yaml` without `workflows` permission)
stderrerror: failed to push some refs to 'https<SCRUBBED>@github.com/project-chip/connectedhomeip.git'
stderrWe had trouble running a system command:
stderr
stderr  callProcess: git "push" "--force-with-lease" "origin" "restyled/pull-9405" (exit
stderr  1): failed

```yaml
# .restyled.yaml as it was in the commit for the Job
```

**Comment by pbrisbin** [comment]
Hi there, sorry for the trouble. Unfortunately, you've hit [this common error](https://github.com/restyled-io/restyled.io/wiki/Common-Errors:-Push-Rejected#refusing-to-allow-a-bot). Please check that link for more details and possible workarounds.
