### ISSUE TITLE
Problem with Restyler Job #1141424

### ISSUE THREAD

**Issue by KochankovID** [restyled-io/restyler#163]
Please use the below template to report an issue with this Job. **Don't submit
sensitive information**, this is a public project. If you'd rather communicate
privately, email support@restyled.io.

---

Hi there-

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/KochankovID/repos/TonalCreamAssistant/jobs/1141424
- **GitHub PR**: KochankovID/TonalCreamAssistant#10

**What I expected to happen**:
No refactorings found

**What happened instead**:
 Error restyling

**Configuration** (if applicable):
the problem is appear to be in yapf:
(from logs)
yapf: toml package is needed for using pyproject.toml as a configuration file
[Info] Setting status of error for eb11dc1
We had trouble with the yapf restyler:
  Exited non-zero (1) for the following paths,

```yaml
# .restyled.yaml as it was in the commit for the Job
```

**Comment by pbrisbin** [comment]
Thanks for the details!

I think we'd just have to install that package in the yapf restyler, which would happen here: https://github.com/restyled-io/restylers/blob/main/yapf/requirements.txt.

Do you want to try a PR? Otherwise, I'll stick it on my TODOs.

**Comment by KochankovID** [comment]
@pbrisbin thank you for your fast response! I've created PR)

**Comment by pbrisbin** [comment]
Thank you!

It looks like that merged and was released. It goes to the `dev` channel right away, and will be in `stable` within a week.
