### ISSUE TITLE
Problem with Restyler Job #2281944

### ISSUE THREAD

**Issue by mrhappyma** [restyled-io/restyler#184]
---

Hi there-

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/mrhappyma/repos/vacuum/jobs/2281944
- **GitHub PR**: mrhappyma/vacuum#10

Logs:
```
info     Restyler starting              
debug    Switched to branch 'pull-10'   
info     Restyling PR                    number=10
info     No existing Restyled PR        
info     Cloning repository             
info     Fetching remote file            path="/tmp/restylers-stable.yaml"
info     Restyling                       paths=["package.json"] restyler="jq"
info     Restyling                       paths=["tsconfig.json"] restyler="jq"
debug    parse error: Invalid numeric literal at line 3, column 7
info     Setting PR status               commit="93e0528" status="error"
error    We had trouble with the jq restyler:

  Exited non-zero (4) for the following paths, ["tsconfig.json"].
  Error information may be present in the stderr output above.

Please see https://stedolan.github.io/jq/

```

**Comment by pbrisbin** [comment]
Hi there-

```
debug    parse error: Invalid numeric literal at line 3, column 7
error    We had trouble with the jq restyler:

Exited non-zero (4) for the following paths, ["tsconfig.json"].
```

It looks like `tsconfig.json` is not a valid JSON file and `jq` is failing trying to parse it.

If that's expected, and you just want `jq` to ignore this file, you can exclude it via your [`restylers` config](https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled#restylers):

```yaml
restylers:
  - jq:
      include:
        - "**/*.json"
        - "!tsconfig.json"
  - "*" 
```

**Comment by mrhappyma** [comment]
I think my `tsconfig.json` was valid, worked fine... regardless restyled is working fine now.

**Comment by pbrisbin** [comment]
Sounds good.

Restyled only runs on changed files. So it's possible it will still error on any PRs that touch that file. `tsconfig.json` can often contain comments, which TypeScript ignores when loading but is not actually valid JSON. I'd be curious to know what was `at line 3, column 7` as of the commit Restyled was running on (the head of PR #10).

Anyway, if you need any more help let me know.
