### ISSUE TITLE
Prettier plugin missing

### ISSUE THREAD

**Issue by mrhappyma** [restyled-io/restyler#196]
---

:wave: -

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/mrhappyma/repos/qbs/jobs/2847171
- **GitHub PR**: mrhappyma/qbs#13

**What I expected to happen**:
Prettier to succeed

**What happened instead**:
[full logs](https://restyled.io/gh/mrhappyma/repos/qbs/jobs/2847171)

this seems to be the culprit:
```debug    [error] Invalid configuration file `README.md`: Cannot find module 'prettier-plugin-tailwindcss'```

**Configuration** (if applicable):

No custom config

please help me :pray:

**Comment by pbrisbin** [comment]
Submitted a bug about the confusing error message https://github.com/prettier/prettier/issues/14366

**Comment by mrhappyma** [comment]
Oh, that makes sense. Thanks so much.

**Comment by mrhappyma** [comment]
Opened restyled-io/restylers#455 to fix this.

**Comment by pbrisbin** [comment]
Just merged #456, so a fix for this should land in `main` (and so `restylers_version: dev`) soon.
