### ISSUE TITLE
Problem with connectedhomeip restyler job #3200639

### ISSUE THREAD

**Issue by bzbarsky-apple** [restyled-io/restyler#205]
See https://restyled.io/gh/project-chip/repos/connectedhomeip/jobs/3200639 and https://restyled.io/gh/project-chip/repos/connectedhomeip/jobs/3200639/log

It looks like the restyler crashed (ran out of memory?  Something else?).

**Comment by pbrisbin** [comment]
This may be a repeat of #194. Let me rotate the instance and see if it comes unstuck. If this solves it again, I'll get work on the backlog to automate instance rotation on a regular basis.

**Comment by pbrisbin** [comment]
Instance rotation occurred between 15:00-15:15ET. Please let me know if have a build run on the same changed files after that time, and if it succeeds now or 137d again.

**Comment by bzbarsky-apple** [comment]
Will do!

**Comment by bzbarsky-apple** [comment]
I am seeing things like https://restyled.io/gh/project-chip/repos/connectedhomeip/jobs/3215477 but that seems like a different issue, with a much clearer error message.

**Comment by pbrisbin** [comment]
That is the same issue, but I improved the error message the other day. This does mean that rotating the underlying instance did not help, so it's possible you have an actual case where google-java-format is using more memory that we're willing to allocate.

**Comment by bzbarsky-apple** [comment]
That is entirely possible, because the java files involved are ... very large.  OK, thanks!  We will need to figure out what to do with that.

There's no way we can configure the memory allocated via the configuration YAML, right?

**Comment by pbrisbin** [comment]
> There's no way we can configure the memory allocated via the configuration YAML, right?

Unfortunately not, this constraint is sort of a security/reliability/cost thing. We don't want to give folks a knob that can let them turn themselves into a noisy-neighbor problem. This is the sort of thing that _could_ offer some day as a paid feature (it's no different than paying for bigger job-runners on CI), but I just haven't built anything to do that logistically yet. If that's something you'd be interested, I'd love to talk more about it.

Hopefully some of the suggestions in that help doc can work for you though!
