### ISSUE TITLE
Problem with Restyler Job #3245980

### ISSUE THREAD

**Issue by ankurgoel-apeejay** [restyled-io/restyler#207]
Please use the below template to report an issue with this Job. **Don't submit
sensitive information**, this is a public project. If you'd rather communicate
privately, email support@restyled.io.

Before reporting, please check the _Common Errors_ section found in [the wiki](https://github.com/restyled-io/restyled.io/wiki)
sidebar.

---

Hi there-

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/apeejay-education/repos/fabs/jobs/3245980
- **GitHub PR**: apeejay-education/fabs#28

**What I expected to happen**:
It should work, I have github student pack

**What happened instead**:
No Marketplace plan for the owner of this repository (apeejay-education)
For additional help, please see: https://github.com/restyled-io/restyled.io/wiki/Common-Errors:-Plan-Upgrade-Required
You can upgrade your plan at https://github.com/marketplace/restyled-io error={description:"plan upgrade required",exitCode:3,severity:"warning",tag:"plan-upgrade-required"}

_Please try to be specific. Avoid saying "it failed" or "it errored"; instead,
copy over any error messages or other details when available._

**Configuration** (if applicable):

**Comment by pbrisbin** [comment]
Hi there!

Sorry for the trouble. I was unable to find any log messages related to you authorizing Restyled with GitHub and us verifying your student status. Do you mind revisiting https://restyled.io/github-students and clicking the button at the bottom?

Once you do that, it should produce a log message that I can see to help debug. If this is the first time you're doing that, that would explain things and may just get it working too.
