### ISSUE TITLE
Restyling fails with "unknown executable: lua"

### ISSUE THREAD

**Issue by bzbarsky-apple** [restyled-io/restyler#208]
When I try to run
```
exec docker run -it --rm \
  --env DEBUG=1 \
  --env HOST_DIRECTORY="$PWD" \
  --env UNRESTRICTED=1 \
  --volume "$PWD":/code \
  --volume /tmp:/tmp \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --entrypoint restyle-path \
  "restyled/restyler:master-final" filenames here
```
I get:
```
[info] Fetching remote file: /tmp/restylers-stable.yaml
restyle-path: ConfigErrorInvalidRestylersYaml (AesonException "Error in $[19].interpreters[0]: Unknown executable: lua")
```

This used to work a few days ago...

**Comment by bzbarsky-apple** [comment]
This _may_ be related to the failure at https://restyled.io/gh/project-chip/repos/connectedhomeip/jobs/3275564 or that might be a different error...

**Comment by bzbarsky-apple** [comment]
> 1- restyled/restyler:master-final is no longer the image to use, you want restyled/restyler:edge

I see.  I was using an old version of restyle-path, which had the old thing. 

> I would just do an explicit docker pull restyled/restyler:edge

When I do that, I get:

```
% docker pull restyled/restyler:edge
edge: Pulling from restyled/restyler
no matching manifest for linux/arm64/v8 in the manifest list entries
```

and the lua error persists.

>  In the meantime, you can configure the command back to what the older image expects

Will look into that, thanks!

**Comment by pbrisbin** [comment]
> no matching manifest for linux/arm64/v8 in the manifest list entries

Hmm. We don't, and never did, build images for arm64. See https://github.com/restyled-io/restylers/issues/468. I'm not clear how the `:master-final` image was ever working for you before. :thinking: 

I could probably update our build to produce an arm image for the main `restyled/restyler` one -- that'd be much less work than trying to do it for every individual restyler.

**Comment by bzbarsky-apple** [comment]
```
docker pull --platform linux/amd64 restyled/restyler:edge
```
did resolve the lua issue.

**Comment by pbrisbin** [comment]
Makes sense. It seems you can pull and run `amd64` images, if you do so explicitly.
