### ISSUE TITLE
Problem with Restyler Job #197965

### ISSUE THREAD

**Issue by Malik-Saifullah** [restyled-io/restyler#76]
Please use the below template to report an issue with this Job. **Don't submit
sensitive information**, this is a public project. If you'd rather communicate
privately, email support@restyled.io.

---

Hi there-

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/Malik-Saifullah/repos/Akhuwat/jobs/197965
- **GitHub PR**: Malik-Saifullah/Akhuwat#2

**What I expected to happen**:

**What happened instead**:

**Configuration** (if applicable):

```yaml
# .restyled.yaml as it was in the commit for the Job
```

**Comment by pbrisbin** [comment]
:wave: @Malik-Saifullah, sorry to hear you're having an issue with your Job. Unfortunately, without filling in the details, I won't be able to help. I'm going to close for now, but feel free to edit the description with some more details and re-open. Cheers!
