### ISSUE TITLE
Add ESLint Support

### ISSUE THREAD

**Issue by diligamer** [restyled-io/restyler#83]

**Comment by pbrisbin** [comment]
Oh, does ESLint have an auto-fix feature now?

**Comment by diligamer** [comment]
No, Support For ESLint So We Can Use It's styling.

**Comment by pbrisbin** [comment]
I'm not sure I understand, can you say more?

For context, Restyled automatically fixes incorrect style by running some auto-fixer (like Prettier). If ESLint can only point out bad style, but not automatically correct it, I'm not sure what Restyled would do with that information.
