### ISSUE TITLE
Enhanced On-Boarding

### ISSUE THREAD

**Issue by pbrisbin** [restyled-io/restyler#87]
Brain-storming a new on-boarding approach:

1. Change Restyler to do nothing if a `.restyled.yaml` is not present
1. On installation, open a PR with a `.restyled.yaml` (just `enabled: true`)
1. Use that PR's description to provide support and details for a smooth on-boarding

Concerns:

1. I like the current "Just install and go" approach, it's super fast to get value
1. What happens to already-on-boarded repositories with no configuration?

Reference: #84

**Comment by iphydf** [comment]
I like install and go, and I don't like to litter my 35 repos with 35 restyler configs that need to be kept in sync.
