### ISSUE TITLE
Branches not removed after closing Restyle PRs

### ISSUE THREAD

**Issue by pbrisbin** [restyled-io/restyler#95]
Regression from the work to name branches `restyled/x`, instead of `x-restyled`.

Need to restore the call to [`deleteReference`](https://github.com/restyled-io/restyler/blob/master/src/GitHub/Endpoints/GitData/References/Delete.hs) near (or as part of)  [`closeRestyledPullRequest`](https://github.com/restyled-io/restyler/blob/master/src/Restyler/RestyledPullRequest.hs#L179).

**Comment by pbrisbin** [comment]
@iphydf can you let me know if this is fixed for you now?

**Comment by iphydf** [comment]
https://github.com/TokTok/py-toxcore-c/branches it doesn't seem so. Maybe it will work for new ones, but this one (pull-58) wasn't deleted when the PR was closed.

**Comment by iphydf** [comment]
https://github.com/TokTok/toxins/pull/20 is another PR that has an associated restyled PR: https://github.com/TokTok/toxins/pull/24. Soon, 20 will be rebased on master, which will resolve the style issues, causing 24 to be closed.

**Comment by pbrisbin** [comment]
Yeah, you can see the error here: https://restyled.io/gh/TokTok/repos/c-toxcore/jobs/269151

It seems like the API call with the `/` in the branch-name is not being handled correctly. I'm not actually sure how you're supposed to craft the API call, so I'll have to do some testing.

**Comment by pbrisbin** [comment]
Oh, maybe it's because I'm not prefixing this with `heads/`. I'll start with some git-diving to see if the pre-regression code did that.

**Comment by pbrisbin** [comment]
Yes, that's it:

https://github.com/restyled-io/restyler/blob/c265572aaa68a4625eba9b20bdc769f20f8ea627/src/Restyler/PullRequest/Restyled.hs#L175-L178

OK, should be (really) fixed soon.

**Comment by iphydf** [comment]
```@restyled-io restyled-io bot deleted the restyled/pull-31 branch 24 seconds ago```

Looks good now.
