### ISSUE TITLE
Check alternative locations for .restyled.yaml

### ISSUE THREAD

**Issue by pbrisbin** [restyled-io/restyler#98]
Check the following in order, first found is used.

- `.restyled.yaml` (current)
- `.restyled.yml`
- `.github/restyled.yaml`
- `.github/restyled.yml`

**Comment by chiroptical** [comment]
I was able to build and test restyler locally and would like to try to add this enhancement. I see https://github.com/restyled-io/restyler/blob/master/src/Restyler/Config.hs#L203, it should be a simple change using https://hackage.haskell.org/package/base-4.14.0.0/docs/Data-List.html#v:find. I'll need to think more carefully about how to test it.

**Comment by pbrisbin** [comment]
Sounds great! I'm happy to review any WIP, if you get started but have questions.

I'm not sure `Data.List.find` would be useful here, since you probably want to iterate over a list of paths in `IO` and halt on the first one that exists. I suspect you'd just want to change `locaConfigFrom` to accept `[ConfigSource]`, and then `configFile` to `configFiles`.

For testing, there is a way to run an `RIO App a` with a mocked file system ([example](https://github.com/restyled-io/restyler/blob/master/test/Restyler/ConfigSpec.hs#L284-L285)), which means you should be able to call `loadConfigFrom` with various files present and assert the desired outcomes.
